### ISSUE TITLE
Boost C++ symbol-mangling mismatch between compile-time and prebuilt libaries

### ISSUE THREAD

**Issue by steakknife** [libyui/libyui#82] opened 2022-09-11 02:53 UTC
```
[ 96%] Building CXX object src/CMakeFiles/libyui.dir/YWizard.cc.o
[ 97%] Linking CXX shared library libyui.dylib
[ 97%] Built target libyui
[ 98%] Building CXX object tests/CMakeFiles/FSize_test.dir/FSize_test.cc.o
[100%] Linking CXX executable FSize_test
Undefined symbols for architecture arm64:
  "__ZN5boost10test_tools9tt_detail15print_log_valueIPKcEclERSoS4_", referenced from:
      __ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIPKcEERKS8_EclERSo in FSize_test.cc.o
  "__ZN5boost10test_tools9tt_detail15print_log_valueIbEclERSob", referenced from:
      __ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo in FSize_test.cc.o
  "__ZN5boost9unit_test9ut_detail24normalize_test_case_nameB5cxx11ENS0_13basic_cstringIKcEE", referenced from:
      __ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m in FSize_test.cc.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [tests/FSize_test] Error 1
make[1]: *** [tests/CMakeFiles/FSize_test.dir/all] Error 2
make: *** [all] Error 2
```

<details>
<summary>Complete error log</summary>

```
❯ brew install libyui --verbose --debug
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/libyui.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/zstd.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/lz4.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/Users/ba/.homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
==> Downloading https://github.com/libyui/libyui/archive/refs/tags/4.3.3.tar.gz
/Users/ba/.homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.5.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/libyui/libyui/archive/refs/tags/4.3.3.tar.gz
Already downloaded: /Users/ba/Library/Caches/Homebrew/downloads/9e229a02510d4870cf67d6aa3908ee266f1765e451cf9ffa5ba482889a5d169a--libyui-4.3.3.tar.gz
==> Verifying checksum for '9e229a02510d4870cf67d6aa3908ee266f1765e451cf9ffa5ba482889a5d169a--libyui-4.3.3.tar.gz'
/Users/ba/.homebrew/Library/Homebrew/shims/shared/git --version
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/zstd.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/lz4.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/Users/ba/.homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Users/ba/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
tar --extract --no-same-owner --file /Users/ba/Library/Caches/Homebrew/downloads/9e229a02510d4870cf67d6aa3908ee266f1765e451cf9ffa5ba482889a5d169a--libyui-4.3.3.tar.gz --directory /private/tmp/d20220910-47478-15wz6mk
cp -pR /private/tmp/d20220910-47478-15wz6mk/libyui-4.3.3/. /private/tmp/libyui-20220910-47478-1dckqze/libyui-4.3.3
chmod -Rf +w /private/tmp/d20220910-47478-15wz6mk
==> cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/ba/.homebrew/Cellar/libyui/4.3.3 -DBUILD_EXAMPLES=off -DLEGACY_BUILDTOOLS=off ../
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/ba/.homebrew/Library/Homebrew/shims/mac/super/gcc-12 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/ba/.homebrew/Library/Homebrew/shims/mac/super/g++-12 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_INSTALL_PREFIX: /Users/ba/.homebrew/Cellar/libyui/4.3.3
-- Found Boost: /Users/ba/.homebrew/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0") found components: unit_test_framework
-- Found Boost: /Users/ba/.homebrew/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/libyui-20220910-47478-1dckqze/libyui-4.3.3/libyui/build
==> make -j
[  3%] Building CXX object src/CMakeFiles/libyui.dir/YOptionalWidgetFactory.cc.o
[  5%] Building CXX object src/CMakeFiles/libyui.dir/YSettings.cc.o
[  5%] Building CXX object src/CMakeFiles/libyui.dir/YWidgetFactory.cc.o
[  5%] Building CXX object src/CMakeFiles/libyui.dir/YUI.cc.o
[  5%] Building CXX object src/CMakeFiles/libyui.dir/YApplication.cc.o
[  6%] Building CXX object src/CMakeFiles/libyui.dir/YPath.cc.o
[  8%] Building CXX object src/CMakeFiles/libyui.dir/YExternalWidgets.cc.o
[  9%] Building CXX object src/CMakeFiles/libyui.dir/YEvent.cc.o
[ 10%] Building CXX object src/CMakeFiles/libyui.dir/YDialogSpy.cc.o
[ 11%] Building CXX object src/CMakeFiles/libyui.dir/YCommandLine.cc.o
[ 12%] Building CXX object src/CMakeFiles/libyui.dir/YEventFilter.cc.o
[ 13%] Building CXX object src/CMakeFiles/libyui.dir/YEnvVar.cc.o
[ 15%] Building CXX object src/CMakeFiles/libyui.dir/YItem.cc.o
[ 16%] Building CXX object src/CMakeFiles/libyui.dir/YIconLoader.cc.o
[ 17%] Building CXX object src/CMakeFiles/libyui.dir/YMacro.cc.o
[ 19%] Building CXX object src/CMakeFiles/libyui.dir/YShortcut.cc.o
[ 20%] Building CXX object src/CMakeFiles/libyui.dir/YMenuItem.cc.o
[ 20%] Building CXX object src/CMakeFiles/libyui.dir/YSimpleEventHandler.cc.o
[ 22%] Building CXX object src/CMakeFiles/libyui.dir/YShortcutManager.cc.o
[ 23%] Building CXX object src/CMakeFiles/libyui.dir/YTableHeader.cc.o
[ 24%] Building CXX object src/CMakeFiles/libyui.dir/YSingleChildContainerWidget.cc.o
[ 25%] Building CXX object src/CMakeFiles/libyui.dir/YProperty.cc.o
[ 26%] Building CXX object src/CMakeFiles/libyui.dir/YTableItem.cc.o
[ 27%] Building CXX object src/CMakeFiles/libyui.dir/YTreeItem.cc.o
[ 29%] Building CXX object src/CMakeFiles/libyui.dir/YUIException.cc.o
[ 30%] Building CXX object src/CMakeFiles/libyui.dir/YWidgetID.cc.o
[ 32%] Building CXX object src/CMakeFiles/libyui.dir/YUILog.cc.o
[ 32%] Building CXX object src/CMakeFiles/libyui.dir/YUILoader.cc.o
[ 38%] Building CXX object src/CMakeFiles/libyui.dir/YButtonBox.cc.o
[ 38%] Building CXX object src/CMakeFiles/libyui.dir/YAlignment.cc.o
[ 38%] Building CXX object src/CMakeFiles/libyui.dir/YSimpleInputField.cc.o
[ 38%] Building CXX object src/CMakeFiles/libyui.dir/YCheckBox.cc.o
[ 38%] Building CXX object src/CMakeFiles/libyui.dir/YUIPlugin.cc.o
[ 39%] Building CXX object src/CMakeFiles/libyui.dir/YSelectionWidget.cc.o
[ 40%] Building CXX object src/CMakeFiles/libyui.dir/YBusyIndicator.cc.o
[ 41%] Building CXX object src/CMakeFiles/libyui.dir/YCheckBoxFrame.cc.o
[ 43%] Building CXX object src/CMakeFiles/libyui.dir/YBarGraph.cc.o
[ 45%] Building CXX object src/CMakeFiles/libyui.dir/YFrame.cc.o
[ 45%] Building CXX object src/CMakeFiles/libyui.dir/YImage.cc.o
[ 46%] Building CXX object src/CMakeFiles/libyui.dir/YLabel.cc.o
[ 47%] Building CXX object src/CMakeFiles/libyui.dir/YDumbTab.cc.o
[ 50%] Building CXX object src/CMakeFiles/libyui.dir/YItemSelector.cc.o
[ 50%] Building CXX object src/CMakeFiles/libyui.dir/YContextMenu.cc.o
[ 53%] Building CXX object src/CMakeFiles/libyui.dir/YInputField.cc.o
[ 53%] Building CXX object src/CMakeFiles/libyui.dir/YDialog.cc.o
[ 53%] Building CXX object src/CMakeFiles/libyui.dir/YDialogHelpers.cc.o
[ 54%] Building CXX object src/CMakeFiles/libyui.dir/YLogView.cc.o
[ 59%] Building CXX object src/CMakeFiles/libyui.dir/YIntField.cc.o
[ 59%] Building CXX object src/CMakeFiles/libyui.dir/YLayoutBox.cc.o
[ 60%] Building CXX object src/CMakeFiles/libyui.dir/YDownloadProgress.cc.o
[ 60%] Building CXX object src/CMakeFiles/libyui.dir/YComboBox.cc.o
[ 61%] Building CXX object src/CMakeFiles/libyui.dir/YMenuBar.cc.o
[ 63%] Building CXX object src/CMakeFiles/libyui.dir/YMultiLineEdit.cc.o
[ 63%] Building CXX object src/CMakeFiles/libyui.dir/YEmpty.cc.o
[ 63%] Building CXX object src/CMakeFiles/libyui.dir/YGraph.cc.o
[ 76%] Building CXX object src/CMakeFiles/libyui.dir/YRpmGroupsTree.cc.o
[ 76%] Building CXX object src/CMakeFiles/libyui.dir/YTimeField.cc.o
[ 76%] Building CXX object src/CMakeFiles/libyui.dir/YDateField.cc.o
[ 76%] Building CXX object src/CMakeFiles/libyui.dir/YMenuButton.cc.o
[ 77%] Building CXX object src/CMakeFiles/libyui.dir/YRadioButtonGroup.cc.o
[ 77%] Building CXX object src/CMakeFiles/libyui.dir/YProgressBar.cc.o
[ 77%] Building CXX object src/CMakeFiles/libyui.dir/YMultiProgressMeter.cc.o
[ 79%] Building CXX object src/CMakeFiles/libyui.dir/YSquash.cc.o
[ 80%] Building CXX object src/CMakeFiles/libyui.dir/YMultiSelectionBox.cc.o
[ 80%] Building CXX object src/CMakeFiles/libyui.dir/YMenuWidget.cc.o
[ 80%] Building CXX object src/CMakeFiles/libyui.dir/YPackageSelector.cc.o
[ 81%] Building CXX object src/CMakeFiles/libyui.dir/YSlider.cc.o
[ 81%] Building CXX object src/CMakeFiles/libyui.dir/YWizard.cc.o
[ 82%] Building CXX object src/CMakeFiles/libyui.dir/YPopupInternal.cc.o
[ 84%] Building CXX object src/CMakeFiles/libyui.dir/YRadioButton.cc.o
[ 84%] Building CXX object src/CMakeFiles/libyui.dir/YTable.cc.o
[ 87%] Building CXX object src/CMakeFiles/libyui.dir/YReplacePoint.cc.o
[ 88%] Building CXX object src/CMakeFiles/libyui.dir/YTree.cc.o
[ 88%] Building CXX object src/CMakeFiles/libyui.dir/YPartitionSplitter.cc.o
[ 88%] Building CXX object src/CMakeFiles/libyui.dir/YSelectionBox.cc.o
[ 89%] Building CXX object src/CMakeFiles/libyui.dir/YPushButton.cc.o
[ 91%] Building CXX object src/CMakeFiles/libyui.dir/YSpacing.cc.o
[ 94%] Building CXX object src/CMakeFiles/libyui.dir/FSize.cc.o
[ 94%] Building CXX object src/CMakeFiles/libyui.dir/YTimezoneSelector.cc.o
[ 94%] Building CXX object src/CMakeFiles/libyui.dir/YStringTree.cc.o
[ 94%] Building CXX object src/CMakeFiles/libyui.dir/YWidget.cc.o
[ 95%] Building CXX object src/CMakeFiles/libyui.dir/YRichText.cc.o
[ 96%] Building CXX object src/CMakeFiles/libyui.dir/YPropertyEditor.cc.o
[ 97%] Linking CXX shared library libyui.dylib
[ 97%] Built target libyui
[ 98%] Building CXX object tests/CMakeFiles/FSize_test.dir/FSize_test.cc.o
[100%] Linking CXX executable FSize_test
Undefined symbols for architecture arm64:
  "__ZN5boost10test_tools9tt_detail15print_log_valueIPKcEclERSoS4_", referenced from:
      __ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIPKcEERKS8_EclERSo in FSize_test.cc.o
  "__ZN5boost10test_tools9tt_detail15print_log_valueIbEclERSob", referenced from:
      __ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo in FSize_test.cc.o
  "__ZN5boost9unit_test9ut_detail24normalize_test_case_nameB5cxx11ENS0_13basic_cstringIKcEE", referenced from:
      __ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m in FSize_test.cc.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [tests/FSize_test] Error 1
make[1]: *** [tests/CMakeFiles/FSize_test.dir/all] Error 2
make: *** [all] Error 2
/Users/ba/.homebrew/Library/Homebrew/shims/shared/git --version
/Users/ba/.homebrew/Library/Homebrew/shims/shared/curl --version
/Users/ba/.homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
BuildError: Failed executing: make -j
```

</details>

<details>
<summary>Similar symbols</summary>

```
0000000000000004 T __ZN5boost10test_tools9tt_detail15print_log_valueIbEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEb
0000000000000028 T __ZN5boost10test_tools9tt_detail15print_log_valueIcEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEc
000000000000010c T __ZN5boost10test_tools9tt_detail15print_log_valueIhEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEh
000000000000014c T __ZN5boost10test_tools9tt_detail15print_log_valueIwEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEw
000000000000029c T __ZN5boost10test_tools9tt_detail15print_log_valueIPKcEclERNSt3__113basic_ostreamIcNS6_11char_traitsIcEEEES4_
00000000000002dc T __ZN5boost10test_tools9tt_detail15print_log_valueIPKwEclERNSt3__113basic_ostreamIcNS6_11char_traitsIcEEEES4_
0000000000020984 T __ZN5boost10test_tools9tt_detail15print_log_valueIbEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEb
00000000000209a8 T __ZN5boost10test_tools9tt_detail15print_log_valueIcEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEc
0000000000020a8c T __ZN5boost10test_tools9tt_detail15print_log_valueIhEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEh
0000000000020acc T __ZN5boost10test_tools9tt_detail15print_log_valueIwEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEw
0000000000020c1c T __ZN5boost10test_tools9tt_detail15print_log_valueIPKcEclERNSt3__113basic_ostreamIcNS6_11char_traitsIcEEEES4_
0000000000020c5c T __ZN5boost10test_tools9tt_detail15print_log_valueIPKwEclERNSt3__113basic_ostreamIcNS6_11char_traitsIcEEEES4_
```

[Enumeration of all symbols in boost libraries](https://gist.github.com/steakknife/2a14d0793c3d3f0590241e1e6159a7ca)
</details>

<details>
<summary>Boost formula (unchanged from default) </summary>

```ruby
class Boost < Formula
  desc "Collection of portable C++ source libraries"
  homepage "https://www.boost.org/"
  url "https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2"
  sha256 "475d589d51a7f8b3ba2ba4eda022b170e562ca3b760ee922c146b6c65856ef39"
  license "BSL-1.0"
  revision 2
  head "https://github.com/boostorg/boost.git", branch: "master"

  livecheck do
    url "https://www.boost.org/users/download/"
    regex(/href=.*?boost[._-]v?(\d+(?:[._]\d+)+)\.t/i)
    strategy :page_match do |page, regex|
      page.scan(regex).map { |match| match.first.tr("_", ".") }
    end
  end

  bottle do
    sha256 cellar: :any,                 arm64_monterey: "0d9c01b3a721dea9799d80908f4c844f97eb12dc2ac5ac1a075264ca8a387bc8"
    sha256 cellar: :any,                 arm64_big_sur:  "cbdb8f401792700b78546e6345c6e68bff3f1ab2c690168bb2783d98d0141da7"
    sha256 cellar: :any,                 monterey:       "99d46af21309a6df674a3fb8f870cd4da81f8bb4e75b02b56c506161f89dd7a4"
    sha256 cellar: :any,                 big_sur:        "e0dc7e421e9b8359399729f9092edfbd4c1c90f64e8504edbcd0bfdbd747d5ac"
    sha256 cellar: :any,                 catalina:       "40180c497e090fcb6e3494bd639534d7427372a2276015f7c67dbd08ea753456"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "2fca78d431ee8a68474967ffaa3e1796eece997a2379fe9c851fd2dcc4038245"
  end

  depends_on "icu4c"
  depends_on "xz"
  depends_on "zstd"

  uses_from_macos "bzip2"
  uses_from_macos "zlib"

  def install
    # Force boost to compile with the desired compiler
    open("user-config.jam", "a") do |file|
      if OS.mac?
        file.write "using darwin : : #{ENV.cxx} ;\n"
      else
        file.write "using gcc : : #{ENV.cxx} ;\n"
      end
    end

    # libdir should be set by --prefix but isn't
    icu4c_prefix = Formula["icu4c"].opt_prefix
    bootstrap_args = %W[
      --prefix=#{prefix}
      --libdir=#{lib}
      --with-icu=#{icu4c_prefix}
    ]

    # Handle libraries that will not be built.
    without_libraries = ["python", "mpi"]

    # Boost.Log cannot be built using Apple GCC at the moment. Disabled
    # on such systems.
    without_libraries << "log" if ENV.compiler == :gcc

    bootstrap_args << "--without-libraries=#{without_libraries.join(",")}"

    # layout should be synchronized with boost-python and boost-mpi
    args = %W[
      --prefix=#{prefix}
      --libdir=#{lib}
      -d2
      -j#{ENV.make_jobs}
      --layout=tagged-1.66
      --user-config=user-config.jam
      install
      threading=multi,single
      link=shared,static
    ]

    # Boost is using "clang++ -x c" to select C compiler which breaks C++14
    # handling using ENV.cxx14. Using "cxxflags" and "linkflags" still works.
    args << "cxxflags=-std=c++14"
    args << "cxxflags=-stdlib=libc++" << "linkflags=-stdlib=libc++" if ENV.compiler == :clang

    system "./bootstrap.sh", *bootstrap_args
    system "./b2", "headers"
    system "./b2", *args
  end

  test do
    (testpath/"test.cpp").write <<~EOS
      #include <boost/algorithm/string.hpp>
      #include <boost/iostreams/device/array.hpp>
      #include <boost/iostreams/device/back_inserter.hpp>
      #include <boost/iostreams/filter/zstd.hpp>
      #include <boost/iostreams/filtering_stream.hpp>
      #include <boost/iostreams/stream.hpp>

      #include <string>
      #include <iostream>
      #include <vector>
      #include <assert.h>

      using namespace boost::algorithm;
      using namespace boost::iostreams;
      using namespace std;

      int main()
      {
        string str("a,b");
        vector<string> strVec;
        split(strVec, str, is_any_of(","));
        assert(strVec.size()==2);
        assert(strVec[0]=="a");
        assert(strVec[1]=="b");

        // Test boost::iostreams::zstd_compressor() linking
        std::vector<char> v;
        back_insert_device<std::vector<char>> snk{v};
        filtering_ostream os;
        os.push(zstd_compressor());
        os.push(snk);
        os << "Boost" << std::flush;
        os.pop();

        array_source src{v.data(), v.size()};
        filtering_istream is;
        is.push(zstd_decompressor());
        is.push(src);
        std::string s;
        is >> s;

        assert(s == "Boost");

        return 0;
      }
    EOS
    system ENV.cxx, "test.cpp", "-std=c++14", "-o", "test", "-L#{lib}", "-lboost_iostreams",
                    "-L#{Formula["zstd"].opt_lib}", "-lzstd"
    system "./test"
  end
end
```
</details>

<details>
<summary>Brew formula</summary>

```ruby
class Libyui < Formula
  desc "Libyui is a widget abstraction library providing graphical (Qt) and text-based (NCurses) front-ends."
  homepage "https://github.com/libyui/libyui"
  url "https://github.com/libyui/libyui/archive/refs/tags/4.3.3.tar.gz"
  sha256 "fc45079153190e9e7bdf76df9133a24a168af068386574fe3afb40df2a45c2c4"
  license "L/GPL"

  depends_on "cmake" => :build
  depends_on "gcc" => :build

  depends_on "ncurses"
  depends_on "boost"
  depends_on "gettext"

  fails_with :clang

  def install
    ENV.append "LDFLAGS", "-L#{Formula["boost"].opt_lib}"
    ENV.append "LDFLAGS", "-L#{Formula["gettext"].opt_lib}"
    ENV.append "LDFLAGS", "-L#{Formula["ncurses"].opt_lib}"
    ENV.append "LDFLAGS", "-lboost_unit_test_framework"
    ENV.append "LDFLAGS", "-lintl"
    %w[curses form menu ncurses ncurses++ panel].each do |lib|
      ENV.append "LDFLAGS", "-l#{lib}"
      ENV.append "LDFLAGS", "-l#{lib}w"
    end

    chdir "libyui" do
      mkdir "build" do
        system "cmake",
          "-DCMAKE_BUILD_TYPE=Release",
          "-DCMAKE_INSTALL_PREFIX=#{prefix}",
          "../"
        system "make", "-j"
        system "make", "install"
      end
    end

    chdir "libyui-ncurses" do
      mkdir "build" do
        system "cmake",
          "-DCMAKE_BUILD_TYPE=Release",
          "-DCMAKE_INSTALL_PREFIX=#{prefix}",
          "../"
        system "make", "-j"
        system "make", "install"
      end
    end
  end
end
```
</details>

### Platform

- macOS 12.5.1 (21G83) arm64
- gcc 12.2.0
- boost 1.79.0 (with `boost_{log,unit_test_framework}{,-mt}{.a,.dylib}`)
- ncurses 6.3
- gettext 0.21

**Comment by shundhammer** [comment] 2022-09-12 08:07
I don't think any of us has a MacOS X on ARM64 available, so all attempts to debug anything here would be just speculations.

The best thing I can offer you right now is to disable that part; it's just about a single unit test.

https://github.com/libyui/libyui/blob/master/libyui/CMakeLists.txt#L75-L76

```CMake
enable_testing()
add_subdirectory( tests )
```

You can simply comment out those both lines and then run `cmake` again.

You _might_ get the same problem in the `libyui-ncurses/` subdirectory:

https://github.com/libyui/libyui/blob/master/libyui-ncurses/CMakeLists.txt#L18-L19

**Comment by mvidner** [comment] 2022-09-12 11:36
Let's focus on the `bool` instance of the mismatched function.

The following 4 lines are

- provided by boost, mangled
- wanted by libyui, mangled
- provided by boost, demangled
- wanted by libyui, demangled
 
```
0000000000000004 T __ZN5boost10test_tools9tt_detail15print_log_valueIbEclERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEEb
                   __ZN5boost10test_tools9tt_detail15print_log_valueIbEclERSob
boost::test_tools::tt_detail::print_log_value<bool>::operator()(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)
boost::test_tools::tt_detail::print_log_value<bool>::operator()(std::basic_ostream<char, std::char_traits<char> >&, bool)
```

(to demangle the symbols on x86_64 Linux, I had to remove the leading underscore, `sed s/__ZN/_ZN/`)

So there's a spurious(?) namespace named `__1` present in Boost but absent in Libyui. 

When I look for it, <https://duckduckgo.com/?t=ffab&q=std+__1&ia=web> I get to <https://stackoverflow.com/questions/9000816/libc-stop-std-renaming-to-std-1> leading to  <https://stackoverflow.com/questions/8454329/why-cant-clang-with-libc-in-c0x-mode-link-this-boostprogram-options-examp> which says:


> 
> You need to rebuild boost using clang++ -stdlib=libc++.
> 
> libc++ is not binary compatible with gcc's libstdc++ (except for some low level stuff such as operator new). For example the std::string in gcc's libstdc++ is refcounted, whereas in libc++ it uses the "short string optimization". If you were to accidentally mix these two strings in the same program (and mistake them for the same data structure), you would inevitably get a run time crash.
> 
> This accident is exactly what has occurred in your case.
> 
> In order to turn this run time crash into a link time error, libc++ uses a C++11 language feature called inline namespace to change the ABI of std::string without impacting the API of std::string. That is, to you std::string looks the same. But to the linker, std::string is being mangled as if it is in namespace std::__1. Thus the linker knows that std::basic_string and std::__1::basic_string are two different data structures (the former coming from gcc's libstdc++ and the latter coming from libc++).

So I think that you need to inspect the compilation settings Brew uses for Boost and Libyui and make them match.

**Comment by shundhammer** [comment] 2022-09-12 12:02
From @mvidner 's answer AFAICS the problem is on the side of the Brew build environment. Closing.

If there is anything that we can reasonably do from our side to better support that scenario, please let us know what that is and reopen this issue.

**Closed by shundhammer** 2022-09-12 12:02 UTC
